<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\RevitVersions.props"/>

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Nice3point.Revit.Build.Tasks" Version="3.0.1"/>
        <PackageReference Include="Nice3point.Revit.Toolkit" Version="$(RevitVersion).*"/>
        <PackageReference Include="Nice3point.Revit.Extensions" Version="$(RevitVersion).*"/>
        <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*"/>
        <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*"/>
    </ItemGroup>

</Project>
