<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\RevitVersions.props"/>

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>RevitTestRunner.xunitv3.Tests</RootNamespace>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture.Xunit3" Version="4.19.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="xunit.v3" Version="3.1.0" />
        <!--        <PackageReference Include="Nice3point.Revit.Build.Tasks" Version="3.0.1"/>-->
        <!--        <PackageReference Include="Nice3point.Revit.Toolkit" Version="$(RevitVersion).*"/>-->
        <!--        <PackageReference Include="Nice3point.Revit.Extensions" Version="$(RevitVersion).*"/>-->
        <!--        <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*"/>-->
        <!--        <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*"/>-->
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RevitTestLibrary.Common\RevitTestLibrary.Common.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="RevitAPI">
            <HintPath>C:\Program Files\Autodesk\Revit 2025\RevitAPI.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="RevitAPIUI">
            <HintPath>C:\Program Files\Autodesk\Revit 2025\RevitAPIUI.dll</HintPath>
            <Private>true</Private>
        </Reference>
    </ItemGroup>

</Project>
